# Generated by Django 4.2.8 on 2023-12-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=2, max_length=150, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
    ]
