# Generated by Django 5.0 on 2023-12-28 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_brand_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='user_id',
        ),
        migrations.AddField(
            model_name='brand',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
