# Generated by Django 5.0 on 2023-12-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Принято'), (2, 'В процессе'), (3, 'Готово'), (4, 'Завершен')], default=1, verbose_name='Статус'),
        ),
    ]
