# Generated by Django 5.0 on 2023-12-29 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='main.brand', verbose_name='Бренд')),
            ],
        ),
    ]
